use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

use crate::feature::index::{FeatureIndex, FeatureModule};

#[derive(Debug, Deserialize, Serialize)]
pub struct Config {
    pub version: u32,
    pub project: Project,
    #[serde(default, skip_serializing_if = "FeatureSource::is_default")]
    pub feature_source: FeatureSource,
    #[serde(default)]
    pub test_commands: TestCommands,
    #[serde(default)]
    pub discovery: Discovery,
    #[serde(default)]
    pub tests: Vec<TestEntry>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct Project {
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub root: String,
    pub feature: String,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct FeatureSource {
    pub kind: String,
    #[serde(default)]
    pub root: String,
}

impl Default for FeatureSource {
    fn default() -> Self {
        Self {
            kind: "c2rust_feature".to_string(),
            // Empty means: derive from `project.root/.c2rust/<project.feature>`.
            root: String::new(),
        }
    }
}

impl FeatureSource {
    pub fn is_default(&self) -> bool {
        self.kind == "c2rust_feature" && self.root.trim().is_empty()
    }
}

/// Test commands used by `verify` / legacy `check`.
#[derive(Debug, Default, Deserialize, Serialize)]
pub struct TestCommands {
    /// Command to run the C test suite (e.g. `"make test"`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub c: Option<String>,
    /// Command to run the translated Rust test suite.
    ///
    /// This command is executed from `project.root`.  For c2rust-demo output the
    /// generated Cargo project lives under `.c2rust/<feature>/rust`, so a typical
    /// value is `"cd .c2rust/default/rust && cargo test"`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rust: Option<String>,
    /// Optional legacy-compatible extra Rust command; prefer putting the exact
    /// Rust test command in `rust`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub feature_rust: Option<String>,
}

/// Migration status of a single C test.
#[derive(Debug, Clone, Default, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum TestStatus {
    /// Not yet evaluated (default for newly discovered tests).
    #[default]
    Pending,
    /// The test has been ported to Rust; `rust_tests` must be non-empty.
    Ported,
    /// The test is intentionally skipped; `notes` must explain why.
    Skipped,
    /// The test is not applicable to the Rust port.
    NotApplicable,
}

/// A single test-migration entry.
#[derive(Debug, Default, Deserialize, Serialize)]
pub struct TestEntry {
    /// Original C test function name (unique identifier within the manifest).
    pub c_test: String,
    /// Source file path relative to `project.root` where the test was found.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_file: Option<String>,
    /// Migration status.
    #[serde(default)]
    pub status: TestStatus,
    /// Exact selected file entry from c2rust-demo `meta/selected_files.json`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub selected_file: Option<String>,
    /// Generated c2rust-demo module directory under `rust/src/` (e.g. `mod_src_math`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub module: Option<String>,
    /// Symbols generated by c2rust-demo as `fun_*`, `var_*`, or `decl_*` files.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub symbols: Vec<String>,
    /// Rust test names that verify the same behaviour.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub rust_tests: Vec<String>,
    /// Brief description of the migration contract / invariant.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contract: Option<String>,
    /// Free-form notes (required for `skipped` entries).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

#[derive(Debug, Default, Deserialize, Serialize)]
pub struct Discovery {
    #[serde(default)]
    pub paths: Vec<String>,
    #[serde(default)]
    pub extensions: Vec<String>,
    #[serde(default)]
    pub patterns: Vec<DiscoveryPattern>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct DiscoveryPattern {
    pub regex: String,
    #[serde(default)]
    pub framework: String,
}

pub fn load_config(path: &Path) -> Result<Config> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("failed to read config file: {}", path.display()))?;
    let config: Config = serde_yaml::from_str(&content)
        .with_context(|| format!("failed to parse config file: {}", path.display()))?;
    Ok(config)
}

/// Serialize `config` and write it back to `path`.
pub fn save_config(path: &Path, config: &Config) -> Result<()> {
    let content = serde_yaml::to_string(config)
        .with_context(|| "failed to serialize config")?;
    std::fs::write(path, content)
        .with_context(|| format!("failed to write config file: {}", path.display()))?;
    Ok(())
}

/// Resolve `p` relative to the directory that contains `config_path`.
/// Absolute paths are returned unchanged. Empty paths resolve to the config directory.
pub fn resolve_path(config_path: &Path, p: &str) -> PathBuf {
    let relative_to = config_path.parent().unwrap_or_else(|| Path::new("."));
    let joined = if p.trim().is_empty() {
        relative_to.to_path_buf()
    } else {
        relative_to.join(p)
    };
    joined.canonicalize().unwrap_or(joined)
}

/// Resolve the effective `project.root`.
pub fn resolve_project_root(cfg: &Config, config_path: &Path) -> PathBuf {
    resolve_path(config_path, &cfg.project.root)
}

/// Resolve the effective `feature_source.root`, defaulting to
/// `<project.root>/.c2rust/<project.feature>`.
pub fn resolve_feature_root(cfg: &Config, config_path: &Path) -> PathBuf {
    if cfg.feature_source.root.trim().is_empty() {
        resolve_project_root(cfg, config_path)
            .join(".c2rust")
            .join(&cfg.project.feature)
    } else {
        resolve_path(config_path, &cfg.feature_source.root)
    }
}

/// Fill missing manifest fields from the loaded c2rust-demo feature surface.
pub fn apply_surface_defaults(cfg: &mut Config, index: &FeatureIndex) {
    for entry in &mut cfg.tests {
        let mut selected_file = entry.selected_file.clone();
        if selected_file.is_none() {
            selected_file = entry
                .source_file
                .as_deref()
                .and_then(|source_file| infer_selected_file_from_source(index, source_file))
                .map(str::to_owned);
        }

        let mut resolved_module = entry
            .module
            .as_deref()
            .and_then(|name| find_module(index, name));

        if resolved_module.is_none() {
            resolved_module = selected_file
                .as_deref()
                .and_then(|source_file| find_module_for_selected_file(index, source_file));
            if entry.module.is_none() {
                entry.module = resolved_module.map(|module| module.name.clone());
            }
        }

        if entry.selected_file.is_none() {
            if let Some(module) = resolved_module {
                selected_file = selected_file.or_else(|| module.selected_file.clone());
            }
            entry.selected_file = selected_file;
        }

        if entry.symbols.is_empty() {
            if let Some(module) = resolved_module {
                if module.functions.iter().any(|symbol| symbol == &entry.c_test) {
                    entry.symbols.push(entry.c_test.clone());
                }
            }
        }
    }
}

fn infer_selected_file_from_source<'a>(
    index: &'a FeatureIndex,
    source_file: &str,
) -> Option<&'a str> {
    index
        .selected_files
        .iter()
        .find(|selected_file| selected_file.as_str() == source_file)
        .map(String::as_str)
}

fn find_module<'a>(index: &'a FeatureIndex, name: &str) -> Option<&'a FeatureModule> {
    index.modules.iter().find(|module| module.name == name)
}

fn find_module_for_selected_file<'a>(
    index: &'a FeatureIndex,
    selected_file: &str,
) -> Option<&'a FeatureModule> {
    let mut matches = index
        .modules
        .iter()
        .filter(|module| module.selected_file.as_deref() == Some(selected_file));
    let first = matches.next()?;
    if matches.next().is_some() {
        None
    } else {
        Some(first)
    }
}
